DefaultContentLanguage = "en"
author = "Steve Francia"
baseURL = "https://gohugo.io/"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Hugo Themes"
[[menu.main]]
identifier = "author"
name = "Contact Us"
url = "https://www.speakin.co/contact"
weight = 4
[[menu.main]]
identifier = "github-repo-theme"
name = "Become a Client"
url = "https://www.speakin.co/become-a-client"
weight = 3
[[menu.main]]
identifier = "image-credit"
name = "Join as Expert"
url = "https://www.speakin.co/join-as-expert"
weight = 2
[[menu.main]]
identifier = "about"
name = "About Us"
url = "https://www.speakin.co/who-we-are"
weight = 1
[params]
description = "Just a demo site for the Casper3 theme ported to Hugo"
facebook = "https://facebook.com"
github = "https://github.com/jonathanjanssens"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
